roles:
  admin:
    systems:
      - vip
      - daily_scheduler
      - monthly_scheduler
      - field_daily_schedule
      - service_schedule
      - finance_management
      - orders_memo_system
      - staff_payroll
    pages:
      - report
      - log
      - settings
    logs:
      - daily_scheduler
      - field_daily_schedule
      - performance_report
      - service_schedule

  field_only:
    systems:
      - daily_scheduler
      - field_daily_schedule
      - orders_memo_system
    pages:
      - main
      - log
    logs:
      - field_daily_schedule
  cs:
    systems:
      - daily_scheduler
      - orders_memo_system
    pages:
      - main
    logs: []
