users:
  jenny@lemonclean.com.tw:
    password: "jenny"
    role: "admin"

  tpe@lemonclean.com.tw:
    password: "LC42627791"
    role: "field_only"

  taipei@lemonclean.com.tw:
    password: "LC42627791"
    role: "field_only"
